spring:
  r2dbc:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health, info"

info:
  application:
    author: Sangwoo Ra(robbyra@gmail.com)
    version: 0.0.0
    description: Template repository for building Spring Boot(Webflux) Applications using Kotlin
    more_info: https://github.com/sang-w0o/spring-boot-webflux-kotlin-template

jwt:
  secret: ${JWT_SECRET}
  accessTokenExp: 86400000
  refreshTokenExp: 604800000